version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: diploma-blockchain
    environment:
      POSTGRES_USER: kareemabdose
      POSTGRES_PASSWORD: Kabdo-2001
      POSTGRES_DB: diploma-blockchain
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
    driver: bridge
