version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: diploma-verification-db
    environment:
      POSTGRES_USER: kareemabdose
      POSTGRES_PASSWORD: Kabdo-2001
      POSTGRES_DB: diploma-verification
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: diploma-verification-app
    depends_on:
      - db
    environment:
      DB_USER: kareemabdose
      DB_PASSWORD: Kabdo-2001
      DB_NAME: diploma-verification
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

volumes:
  db-data:
